# Generated by Django 3.1.12 on 2022-06-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='job',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='name',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
