# Generated by Django 3.2.6 on 2021-09-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20210903_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='session_id',
            field=models.CharField(max_length=150),
        ),
    ]
