# Generated by Django 3.1.12 on 2022-06-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='forgotten',
            new_name='relevant',
        ),
    ]
